### ISSUE TITLE
"Super table" "Static Field" not saving when display mode is set to Matrix

### ISSUE THREAD

**Issue by K31Z0** [engram-design/SuperTable#185]
### Description
"Super table" "Static Field" not saving when display mode is set to Matrix

### Steps to reproduce

1. Create a Super Table field with "Static field" option enabled
2. Add some dummy fields inside
3. Set the display mode to "Matrix Layout"
4. [Do the usual]
5. Add some dummy content in your fields on the page, save and ... Nothing

### Additional info
When you set the ST field to display mode row or table, all works fine, data's are saved.
With the same field filled with data's you change the display mode to "Matrix Layout" and all the data's disappears.

- Plugin version: 2.0.7
- Craft version: Craft Solo 3.0.20

**Comment by engram-design** [comment]
Please see https://github.com/verbb/super-table/releases/tag/2.0.8 where this was fixed.

**Comment by K31Z0** [comment]
Sorry missed that, the Store version still the 2.0.7 so when I downloaded this morning I didn't had the fix :)

**Comment by engram-design** [comment]
Strange, looks like the plugin store hasn't updated...

**Comment by missmatsuko** [comment]
Has this fix been verified? 

I had the same problem. Updated SuperTable to 2.0.8 and am now getting the 'Global set saved' message. The contents are also there in the CMS fields if I refresh the page. However, I still can't get the data in Twig. Dump shows all field values as null. I do see a craft_stc_[global set name] table in the database that seems to have the right content.

**Comment by engram-design** [comment]
@missmatsuko Something else _may_ be going on in your case. This issue should've affected the field's content when saving. If its showing in the CP and in the database, something else might be amiss. Is this still an issue if you change the layout from Matrix to say Row or Table layout for the field?

Unfortunately, I can't reproduce this, so maybe its worth chatting on the Craft Slack if you have a moment (@crawf).
