### ISSUE TITLE
Can't create new or update existing entries with Super Table fields.

### ISSUE THREAD

**Issue by StudioShand** [engram-design/SuperTable#283]
### Description
At some point since updating Craft and Super Table I can no longer create a new, or update an existing, entry that uses Super Table field/s. All entries that don't include a Super Table field work fine.

I have run both 'Check Content Tables' and 'Re-save Super Table Fields' via Settings > Plugins > Super Table.

### Steps to reproduce

1. Trying to create a new entry that uses a Super Table field results in a 500 error:

```
Error: Class 'verbb\supertable\services\SuperTableBlock' not found in /home/xxxxx.com/craft/vendor/verbb/super-table/src/services/SuperTableService.php:1047
Stack trace:
#0 /home/xxxxx.com/craft/vendor/verbb/super-table/src/services/SuperTableService.php(776): verbb\supertable\services\SuperTableService->_deleteOtherBlocks(Object(verbb\supertable\fields\SuperTableField), Object(craft\elements\Entry), Array)
#1 /home/xxxxx.com/craft/vendor/verbb/super-table/src/fields/SuperTableField.php(857): verbb\supertable\services\SuperTableService->saveField(Object(verbb\supertable\fields\SuperTableField), Object(craft\elements\Entry))
#2 /home/xxxxx.com/craft/vendor/craftcms/cms/src/base/Element.php(2072): verbb\supertable\fields\SuperTableField->afterElementPropagate(Object(craft\elements\Entry), true)
#3 /home/xxxxx.com/craft/vendor/craftcms/cms/src/elements/Entry.php(1213): craft\base\Element->afterPropagate(true)
#4 /home/xxxxx.com/craft/vendor/craftcms/cms/src/services/Elements.php(659): craft\elements\Entry->afterPropagate(true)
#5 /home/xxxxx.com/craft/vendor/craftcms/cms/src/services/Drafts.php(201): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#6 /home/xxxxx.com/craft/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php(126): craft\services\Drafts->saveElementAsDraft(Object(craft\elements\Entry), 1)
#7 [internal function]: craft\controllers\EntryRevisionsController->actionCreateDraft(Object(craft\models\Section), Object(craft\models\Site))
#8 /home/xxxxx.com/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /home/xxxxx.com/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /home/xxxxx.com/craft/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('create-draft', Array)
#11 /home/xxxxx.com/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('create-draft', Array)
#12 /home/xxxxx.com/craft/vendor/craftcms/cms/src/web/Application.php(298): yii\base\Module->runAction('entry-revisions...', Array)
#13 /home/xxxxx.com/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entry-revisions...', Array)
#14 /home/xxxxx.com/craft/vendor/craftcms/cms/src/web/Application.php(283): yii\web\Application->handleRequest(Object(craft\web\Request))
#15 /home/xxxxx.com/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /home/xxxxx.com/craft/web/index.php(42): yii\base\Application->run()
#17 {main}
```
2. Trying to update an existing entry that uses a Super Table field stops Craft creating a draft and the 'Update Entry' button remains disabled so that it's impossible to update an entry. The console shows the following error:

```
POST https://xxxxx.com/index.php/craft/actions/entry-revisions/save-draft 500 (Internal Server Error)
send @ jquery.js:9827
ajax @ jquery.js:9424
postActionRequest @ Craft.js:363
saveDraft @ Craft.js:13136
checkForm @ Craft.js:13107
i @ jquery.js:10492
setTimeout (async)
(anonymous) @ Craft.js:12948
i @ jquery.js:10492
(anonymous) @ garnish.js:893
i @ jquery.js:10492
dispatch @ jquery.js:5233
v.handle @ jquery.js:5040

Craft.js:13144 Uncaught TypeError: Cannot read property 'errors' of null
    at s.constructor.<anonymous> (Craft.js:13144)
    at i (jquery.js:10492)
    at Object.error (Craft.js:372)
    at n (jquery.js:3291)
    at Object.fireWith [as rejectWith] (jquery.js:3421)
    at l (jquery.js:9525)
    at XMLHttpRequest.<anonymous> (jquery.js:9775)
(anonymous) @ Craft.js:13144
i @ jquery.js:10492
error @ Craft.js:372
n @ jquery.js:3291
fireWith @ jquery.js:3421
l @ jquery.js:9525
(anonymous) @ jquery.js:9775
load (async)
send @ jquery.js:9794
ajax @ jquery.js:9424
postActionRequest @ Craft.js:363
saveDraft @ Craft.js:13136
checkForm @ Craft.js:13107
i @ jquery.js:10492
setTimeout (async)
(anonymous) @ Craft.js:12948
i @ jquery.js:10492
(anonymous) @ garnish.js:893
i @ jquery.js:10492
dispatch @ jquery.js:5233
v.handle @ jquery.js:5040
```

3. I've tried creating a new test section with a Super Table field. Trying to create a new entry results in the 500 Internal Server Error above. As soon as I remove the Super Table field I can create and edit the entry as normal.

### Additional info

- Plugin version: 2.2.0
- Craft version: 3.2.1

**Comment by engram-design** [comment]
Sorry about that, should be fixed in [2.2.1](https://github.com/verbb/super-table/releases/tag/2.2.1)

**Comment by gusfaria** [comment]
I am having a similar issue, I am using version 2.2.1 and updated to the latest version 2.4.7.
I am unable to add new fields to a pre-existing super-table. Any advice, any ideas on how to fix this?

**Comment by engram-design** [comment]
@gusfaria Are you getting the same error as @shandy ? Or is it more similar to https://github.com/verbb/super-table/issues/333

**Comment by gusfaria** [comment]
Hi @engram-design,
sorry, I actually have a different error. I am trying to edit a pre-existing supertable field and it redirects me to an Internal Server Error page. I am able to create a new supertable field though.
I have run both 'Check Content Tables' and 'Re-save Super Table Fields' via Settings > Plugins > Super Table, but it still doesn't work.

Is there a way I can recreate that field without losing the data?

Sorry, as this seems like the wrong place to comment on my issue.

**Comment by engram-design** [comment]
@gusfaria Are you able to create a new issue and let me know the full stack trace of the Internal Server Error? Make sure that devMode is on

**Comment by gusfaria** [comment]
Hi @engram-design, I was able to figure out.
It was something related to a default value for `max_input_vars` on php.in above version 5.
Thanks for your prompt assistance.
