### ISSUE TITLE
Drag re-order in Matrix fields

### ISSUE THREAD

**Issue by elliotlewis** [engram-design/SuperTable#55]
Probably a JS issue but it's not possible to drag and reorder Matrix rows inside SuperTable as SuperTable is capturing the drag for it's own rows.

**Comment by engram-design** [comment]
Thanks for raising this - although I seem to be able to reorder both the block types and each of the fields contained within them. Are you getting an JS errors in your web console?

**Comment by elliotlewis** [comment]
No JS errors. Here's a screencast of how it's not working. Link will expire in 7 days.

https://www.wetransfer.com/downloads/10e6a74bd2ace9e0a4f4dc730ca3b72b20160316170758/dc7c3ab7b8c0b55a2d2997576aff154220160316170758/d5f1f7

**Comment by engram-design** [comment]
Ah - yep that video explains it perfectly (thanks!). Now fixed in the latest [master](https://github.com/engram-design/SuperTable).

**Comment by elliotlewis** [comment]
Doesn't seem to have fixed it for me. Same issue in 0.4.6.

**Comment by engram-design** [comment]
Hmm - can't seem to reproduce it from my end now - I've setup a field combination exactly as per your video just to be sure. I did just push an additional fix for an inner-Table field (the same issue), which namespaces the move/delete handles. Maybe its worth clearing the Craft cache?

**Comment by elliotlewis** [comment]
I've cleared the cache but still no luck. Have attached my field set-up just in case it's different to yours. It's very straightforward with just 1 matrix field as a row.

![supertable field settings](https://cloud.githubusercontent.com/assets/962132/13917761/9ed24748-ef5a-11e5-8698-a29e4296f838.png)

**Comment by engram-design** [comment]
Well, I'm certainly at a loss here, as its working here (see https://www.dropbox.com/s/513b9gouats5the/supertable_matrix.mov?dl=0).

The only other thing I would try is completely removing the `supertable` folder from your plugin folder, and re-adding from the latest master...

**Comment by engram-design** [comment]
Did we ever get to the bottom of this one?

**Comment by engram-design** [comment]
Closing - no response, but please reopen if this still is an issue.
